/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();
        lb_HidePassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_ShowPassword = new javax.swing.JLabel();
        lb_HidePassword = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("WELCOME TO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel1.setText("NOTIMETOHELL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 480));

        jPanel2.setBackground(new java.awt.Color(7, 29, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM LOGIN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 68, -1, -1));

        lb_ShowPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/eye.png"))); // NOI18N
        lb_ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ShowPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lb_ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 306, 40, 30));

        lb_HidePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/hide.png"))); // NOI18N
        lb_HidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HidePasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lb_HidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 306, 40, 30));

        txt_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(null);
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel2.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 223, 299, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 198, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 279, -1, -1));

        btn_login.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 360, 109, 42));

        txt_pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(null);
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 304, 299, 38));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 116, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 0, 390, 481));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       try{
//            Connection c = koneksi.getKoneksi();
            String url = "jdbc:mysql://localhost:3306/not_found";
            String user = "root";
            String password = "sefin1409";
//            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
//            koneksi = DriverManager.getConnection(url, user, password);
//            System.out.println("Berhasil");
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection(url, user, password);


            String Username = txt_user.getText();
            String Password = txt_pass.getText();
            
            java.sql.Statement stm = c.createStatement();
            String sql = "select * from pengguna where username='"+Username+"' and password='"+Password+"'"; 
            
            ResultSet rs = stm.executeQuery(sql);
            
           if (rs.next()) {
           // Menutup frame login
             String id = rs.getString("id_pengguna");
             String nama_pengguna = rs.getString("nama_pengguna");
             String jabatan = rs.getString("jabatan");
             
              JOptionPane.showMessageDialog(null, "Selamat datang, " + nama_pengguna + " " + jabatan);
              dispose();

            // Membuka frame Main dengan mengirimkan username dan jabatan
            Main ksb = new Main(nama_pengguna, jabatan, id);
            ksb.show(); // Menampilkan frame utama

            // Tampilkan pesan selamat datang
             
            } else {
               JOptionPane.showMessageDialog(null, "Username atau Password salah");
               txt_user.setText("");
               txt_pass.setText("");
            }
            
            
//            c.close();
        } catch(Exception e){
        System.out.println(e);
        
    }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void lb_ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ShowPasswordMouseClicked
        // TODO add your handling code here:
        lb_ShowPassword.setVisible(false);
        lb_HidePassword.setVisible(true);
        txt_pass.setEchoChar((char)0);
    }//GEN-LAST:event_lb_ShowPasswordMouseClicked

    private void lb_HidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HidePasswordMouseClicked
        // TODO add your handling code here:
        lb_ShowPassword.setVisible(true);
        lb_HidePassword.setVisible(false);
        txt_pass.setEchoChar('*');
        
    }//GEN-LAST:event_lb_HidePasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            FrameLogin FL = new FrameLogin();
            FL.setVisible(true);
//            FL.setExtendedState(FrameLogin.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_HidePassword;
    private javax.swing.JLabel lb_ShowPassword;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
